### ISSUE TITLE
Upgrade pybind11 to the latest version

### ISSUE THREAD

**Issue by khalatepradnya** [NVIDIA/cuda-quantum#1046]
* Using pybind11 version 2.11.0+ results in three test failures in 'eager' mode under 'experimental/python' branch. These tests work as expected with pybind11 version 2.10.4.
* When the behavior is modified either on pybind11 or on CUDA Quantum, upgrade pybind11 to latest version.
* Origin:

> This issue was introduced with the update to pybind11 2.11 (appears to be a pybind bug). pybind version 2.10 and below work. Easiest fix would be to lower to pybind 2.10 until a fix appears in a future version. pybind 2.11 (appears to be a pybind bug). pybind version 2.10 and below work. Easiest fix would be to lower to pybind 2.10 until a fix appears in a future version.

_Originally posted by @amccaskey in https://github.com/NVIDIA/cuda-quantum/pull/1001#discussion_r1426640287_

```[tasklist]
### Tasks
- [x] Identify the changes / commit in pybind11 that introduced change in behavior.
- [ ] Check behavior with latest version of pybind11
- [ ] Triage if fix possible on CUDA Quantum
```

**Comment by khalatepradnya** [comment]
Looking at changelog, pybind11 v2.11.0 introduced https://github.com/pybind/pybind11/pull/4631 and https://github.com/pybind/pybind11/pull/4623. These changes recursively check if a type is movable.
Previously pybind11 relied on `std::is_move_constructible`, now, it has own implementation.
Refer test case: https://github.com/pybind/pybind11/blob/master/tests/test_copy_move.cpp#L383
`qview` is copyable but, `qvector` and `qudits` are non-copyable and non-movable. Also, not sure if related, but, `std::span` isn't supported in default bindings. (https://github.com/pybind/pybind11/discussions/4177).

**Comment by khalatepradnya** [comment]
Attempt to reproduce the behavior stand-alone:
1. C++ composite classes in `bar.hpp`
```#pragma once

#include <ranges>
#include <span>
#include <vector>

class NonCopyableNonMovableInt
{
private:
    int num;

public:
    NonCopyableNonMovableInt() {}
    NonCopyableNonMovableInt(int n) : num(n) {}

    NonCopyableNonMovableInt(NonCopyableNonMovableInt const &) = delete;
    NonCopyableNonMovableInt(NonCopyableNonMovableInt &&) = delete;

    int getValue() { return num; }
    void setValue(int n) { num = n; }
};

class SpanOfNoCopyNoMoveVec
{
private:
    std::span<NonCopyableNonMovableInt> num_span;

public:
    template <typename R>
        requires(std::ranges::range<R>)
    SpanOfNoCopyNoMoveVec(R &&other) : num_span(other.begin(), other.end())
    {
    }

    SpanOfNoCopyNoMoveVec(SpanOfNoCopyNoMoveVec const &other) : num_span(other.num_span) {}

    NonCopyableNonMovableInt &operator[](const std::size_t idx)
    {
        return num_span[idx];
    }

    NonCopyableNonMovableInt &front() { return num_span.front(); }

    SpanOfNoCopyNoMoveVec front(std::size_t s) { return num_span.first(s); }

    std::size_t size() const { return num_span.size(); }
};

class NonCopyableNonMovableVector
{
private:
    std::vector<NonCopyableNonMovableInt> nums;

public:
    NonCopyableNonMovableVector(std::vector<int> _nums) : nums(_nums.size())
    {
        for (int i; i < _nums.size(); i++)
        {
            nums[i].setValue(_nums[i]);
        }
    }

    NonCopyableNonMovableVector(NonCopyableNonMovableVector const &) = delete;

    NonCopyableNonMovableVector(NonCopyableNonMovableVector &&) = delete;

    NonCopyableNonMovableInt &operator[](const std::size_t idx)
    {
        return nums[idx];
    }

    NonCopyableNonMovableInt &front() { return nums.front(); }

    SpanOfNoCopyNoMoveVec front(std::size_t s)
    {

        return std::span(nums).subspan(0, s);
    }

    std::size_t size() const { return nums.size(); }

    int getSum()
    {
        int sum = 0;
        for (std::vector<NonCopyableNonMovableInt>::iterator it = nums.begin(); it != nums.end(); ++it)
        {
            sum += it->getValue();
        }
        return sum;
    }
};
```
3. Python bindings for `bar`in `pybind_bar.cpp`
```#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "bar.hpp"

namespace py = pybind11;

PYBIND11_MODULE(bar, m)
{
    py::class_<NonCopyableNonMovableInt>(m, "NonCopyableNonMovableInt")
        .def(py::init<>())
        .def(py::init<int>())
        .def("get_value", &NonCopyableNonMovableInt::getValue)
        .def("set_value", &NonCopyableNonMovableInt::setValue);

    py::class_<SpanOfNoCopyNoMoveVec>(m, "SpanOfNoCopyNoMoveVec")
        .def("__getitem__", &SpanOfNoCopyNoMoveVec::operator[], py::return_value_policy::reference)
        .def("front", py::overload_cast<>(&SpanOfNoCopyNoMoveVec::front))
        .def("front", py::overload_cast<std::size_t>(&SpanOfNoCopyNoMoveVec::front))
        .def("size", &SpanOfNoCopyNoMoveVec::size);

    py::class_<NonCopyableNonMovableVector>(m, "NonCopyableNonMovableVector")
        .def(py::init<std::vector<int>>())
        .def("__getitem__", &NonCopyableNonMovableVector::operator[], py::return_value_policy::reference)
        .def("front", py::overload_cast<>(&NonCopyableNonMovableVector::front), py::return_value_policy::reference)
        .def("front", py::overload_cast<std::size_t>(&NonCopyableNonMovableVector::front))
        .def("size", &NonCopyableNonMovableVector::size)
        .def("get_sum", &NonCopyableNonMovableVector::getSum);
}
```
4. Build with pybind11 version 2.11.1
5. Use in Python
```$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bar
>>> primes = bar.NonCopyableNonMovableVector([2, 3, 5, 7, 11, 13])
>>> print(primes)
<bar.NonCopyableNonMovableVector object at 0x7fc37a6b0270>
>>> x = primes.front()
>>> print(x)
<bar.NonCopyableNonMovableInt object at 0x7fc37a6b0230>
>>> x.get_value()
2
>>> y = primes.front(3)
>>> print(y)
<bar.SpanOfNoCopyNoMoveVec object at 0x7fc37a6b02f0>
>>> exit()
```
6. Unexpected behavior: `enumerate` for loop results in infinite loop:
```
import bar
primes = bar.NonCopyableNonMovableVector([2, 3, 5, 7, 11, 13])
a = primes.front(4)
# Causes infinite loop
    check = 0
    for i, j in enumerate(a):
        assert i == check
        assert j == primes[check]
        check += 1
```
