### ISSUE TITLE
[RFC] Regression tests should be more repeatable

### ISSUE THREAD

**Issue by bmhowe23** [NVIDIA/cuda-quantum#608]
### Required prerequisites

- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to check if your feature has already been mentioned or rejected in other issues.

## Issue

Some of our CI tests are not repeatable (with respect to getting the same answers in back to back runs), and this can cause 2 issues.
1. We don't know if test failures and/or long test runtimes are due to code changes under test or are due to run-to-run variance.
2. It's harder to debug non-repeatable tests.

For example, `nvqpp_VQEH2Builder` can take anywhere from ~20 seconds to >10 minutes.

There are at least 3 reasons for our non-repeatability.
1. We are often generating random numbers to use in our tests, and PR #477 provided a new interface to get repeatably random numbers, but we are not using that capability everywhere that we probably should.
2. Some of our tests use `cudaq::random_vector()` to generate an initial vector for an optimization search. Different initial vectors will lead to very different optimization paths and even optimization results.
3. The OpenMP code is causing slight non-repeatabilities in our _answers_ but huge non-repeatabilities in our _runtimes_. OpenMP chooses a different number of threads based on your specific hardware platform, and on both my machine and an internal NVIDIA machine, the higher thread count is actually hurting our runtime performance in many cases. In fact, the only case where it seems to be helping by any significant amount is in `dm_GHZSampleTester.checkBroadcast` (3.8 seconds with `OMP_NUM_THREADS` left undefined [36 on my machine] and 62.4 seconds with `OMP_NUM_THREADS=1`). All other cases seem to either be unaffected by OpenMP or OpenMP is actually hurting our performance (and repeatability). As alluded to earlier, the difference can be quite large for our `nvqpp_VQEH2Builder` test (~20 seconds w/ 1 thread and >10 minutes with all threads).

## What do we do about it?

This part is obviously up for debate, but I'd recommend we provide a new variant of `cudaq::random_vector()` where we allow the caller to set the seed, and then in the tests that need it, we specify the seed. I believe that is `qaoa_maxcut.cpp`, `vqe_h2.cpp`, `qaoa_max_cut_builder.cpp`, `vqe_h2_builder.cpp`, `ChemistryTester.cpp`, and `mqpu_tester.cpp`. Furthermore, I'd recommend that we find an improved way to set the number of OMP threads. Perhaps that means we set it to 1 for most tests. Or perhaps we find a way to make OpenMP more repeatable.
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cuda-quantum/pull/617
- [ ] https://github.com/NVIDIA/cuda-quantum/pull/648
```

**Comment by bmhowe23** [comment]
@1tnguyen had a good finding described [here](https://github.com/NVIDIA/cuda-quantum/pull/617#discussion_r1319411179). We should probably do his suggestion under a new PR associated with this issue.
