### ISSUE TITLE
Support ranged `for` loops, `std::reverse` iterator modifier, and `cudaq::range`

### ISSUE THREAD

**Issue by schweitzpgi** [NVIDIA/cuda-quantum#646]
These C++ and CUDA quantum features allow a richer set of looping constructs which can give the `nvq++` user a richer programming environment and experience. Mapping these, possibly in combinations, correctly to `cc.loop` should be supported in the bridge.
```[tasklist]
### Tasks
- [x] Add a regression test with nested ranged-for statements
- [ ] Add support for std::reverse
- [x] Add support for cudaq::range
- [ ] Add support for iteration over the quantum collections (qreg, etc.)
- [x] Add support for do-while to while conversion (loop peeling)
- [x] Finish implementation of loop unrolling of while loops
```
